### ISSUE TITLE
SitemapGenerator fails on Ruby 2.6.1 undefined method yaml_as

### ISSUE THREAD

**Issue by mberkowski** [BTAA-Geospatial-Data-Project/geoportal#189]
The sitemap:refresh task is tripping on Ruby 2.6.1 with a `yaml_as` NoMethodError.

```
NoMethodError: undefined method `yaml_as' for SitemapGenerator::BigDecimal:Class
/swadm/var/www/geoblacklight/shared/bundle/ruby/2.6.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/core_ext/big_decimal.rb:15:in `<class:BigDecimal>'
/swadm/var/www/geoblacklight/shared/bundle/ruby/2.6.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/core_ext/big_decimal.rb:11:in `<top (required)>'
/swadm/var/www/geoblacklight/shared/bundle/ruby/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `require'
/swadm/var/www/geoblacklight/shared/bundle/ruby/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `block in require'
/swadm/var/www/geoblacklight/shared/bundle/ruby/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/swadm/var/www/geoblacklight/shared/bundle/ruby/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `require'
/swadm/var/www/geoblacklight/shared/bundle/ruby/2.6.0/gems/sitemap_generator-5.2.0/lib/sitemap_generator/helpers/number_helper.rb:129:in `number_with_precision'
```

**Comment by mberkowski** [comment]
Deployments don't complete entirely due to this issue, but both sitemap and centroids generation tasks occur _after_ the release is symlinked and ready for use. So it is still possible to deploy it by manually running the centroids after the fact:
`RAILS_ENV=production bundle exec rake geoportal:generate_centroids_json`  will succeed.
