### ISSUE TITLE
A lot of ActiveSupport::MessageVerifier::InvalidSignature alerts

### ISSUE THREAD

**Issue by mberkowski** [BTAA-Geospatial-Data-Project/geoportal#380]
These might be nothing, like an invalid SSL cert upstream somewhere. But hundreds a day started in the last 4-5 days.

```
An ActiveSupport::MessageVerifier::InvalidSignature occurred in representations#show:

  ActiveSupport::MessageVerifier::InvalidSignature

-------------------------------
Request:
-------------------------------

  * URL        : https://geo.btaa.org/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEFRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02fdcf31b4ece71359da7220041d4376c08d816a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lJTWpBd0Jqb0dSVlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0\u003d--ba3bf1e7b2fedc83b34679de980c7230e2d4bed0/17c7f190-1243-407c-acca-2f41524dfba920180822-63532-1xdas8.jpeg
  * HTTP Method: GET
  * IP address :
  * Parameters : {"controller"=>"active_storage/representations", "action"=>"show", "signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEFRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02fdcf31b4ece71359da7220041d4376c08d816a", "variation_key"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lJTWpBd0Jqb0dSVlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0\\u003d--ba3bf1e7b2fedc83b34679de980c7230e2d4bed0", "filename"=>"17c7f190-1243-407c-acca-2f41524dfba920180822-63532-1xdas8", "format"=>"jpeg"}
  * Timestamp  : 2021-07-04 10:06:12 -0500
```

## Stack trace from log:
```
F, [2021-07-04T10:06:12.424578 #46179] FATAL -- : [31b43013-912d-4615-b5ef-1c38b8f55dad]   
F, [2021-07-04T10:06:12.424660 #46179] FATAL -- : [31b43013-912d-4615-b5ef-1c38b8f55dad] ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature):
F, [2021-07-04T10:06:12.424689 #46179] FATAL -- : [31b43013-912d-4615-b5ef-1c38b8f55dad]   
F, [2021-07-04T10:06:12.424752 #46179] FATAL -- : [31b43013-912d-4615-b5ef-1c38b8f55dad] activesupport (5.2.6) lib/active_support/message_verifier.rb:176:in `verify'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activestorage (5.2.6) app/models/active_storage/variation.rb:40:in `decode'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activestorage (5.2.6) app/models/active_storage/variation.rb:32:in `wrap'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activestorage (5.2.6) app/models/active_storage/variant.rb:48:in `initialize'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activestorage (5.2.6) app/models/active_storage/blob/representable.rb:30:in `new'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activestorage (5.2.6) app/models/active_storage/blob/representable.rb:30:in `variant'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activestorage (5.2.6) app/models/active_storage/blob/representable.rb:83:in `representation'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activestorage (5.2.6) app/controllers/active_storage/representations_controller.rb:12:in `show'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/abstract_controller/base.rb:194:in `process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activesupport (5.2.6) lib/active_support/callbacks.rb:132:in `run_callbacks'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activesupport (5.2.6) lib/active_support/notifications.rb:168:in `block in instrument'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activesupport (5.2.6) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activesupport (5.2.6) lib/active_support/notifications.rb:168:in `instrument'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activerecord (5.2.6) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/abstract_controller/base.rb:134:in `process'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionview (5.2.6) lib/action_view/rendering.rb:32:in `process'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal.rb:191:in `dispatch'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_controller/metal.rb:252:in `dispatch'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:34:in `serve'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] exception_notification (4.3.0) lib/exception_notification/rack.rb:41:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[31b43013-912d-4615-b5ef-1c38b8f55dad] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] rack (2.2.3) lib/rack/head.rb:12:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[31b43013-912d-4615-b5ef-1c38b8f55dad] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/middleware/cookies.rb:670:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] activesupport (5.2.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[31b43013-912d-4615-b5ef-1c38b8f55dad] actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
```

**Comment by mberkowski** [comment]
As I've watched these come in, they all originate from the same handful of remote IPs, and are probably therefore a bad scan or probe. Let's ignore and it will probably eventually disappear, I don't think we have any code or infra faults.
