### ISSUE TITLE
ActionView::Template::Error: undefined method `symbol' for nil:NilClass

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#4]
Qualys-generated exception hitting `PUT /bookmarks/test_put_qualys1819`

This may be deep in ActiveSupport rather than BL/GBL.

## Request:
-------------------------------
Environment:
-------------------------------

  * CONTENT_LENGTH                                 : 144
  * HTTPS                                          : on
  * HTTP_HOST                                      : lib-geoblacklight.oit.umn.edu
  * HTTP_QUALYS_SCAN                               : VM
  * HTTP_VERSION                                   : HTTP/1.1
  * ORIGINAL_FULLPATH                              : /bookmarks/test_put_qualys1819
 * PATH_INFO                                      : /bookmarks/test_put_qualys1819
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 160.94.202.170
  * REMOTE_PORT                                    : 59282
  * REQUEST_METHOD                                 : PUT
  * REQUEST_URI                                    : /bookmarks/test_put_qualys1819
  * ROUTES_70016276725680_SCRIPT_NAME              :

## Trace:

```
F, [2016-11-17T00:29:53.379971 #1873] FATAL -- : NoMethodError (undefined method `symbol' for nil:NilClass):
F, [2016-11-17T00:29:53.380007 #1873] FATAL -- :   
F, [2016-11-17T00:29:53.380028 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/http/parameters.rb:63:in `parse_formatted_parameters'
F, [2016-11-17T00:29:53.380043 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/http/request.rb:366:in `block in POST'
F, [2016-11-17T00:29:53.380059 #1873] FATAL -- : rack (2.0.1) lib/rack/request.rb:57:in `fetch'
F, [2016-11-17T00:29:53.380085 #1873] FATAL -- : rack (2.0.1) lib/rack/request.rb:57:in `fetch_header'
F, [2016-11-17T00:29:53.380111 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/http/request.rb:365:in `POST'
F, [2016-11-17T00:29:53.380134 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/http/parameters.rb:35:in `parameters'
F, [2016-11-17T00:29:53.380148 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/http/filter_parameters.rb:41:in `filtered_parameters'
F, [2016-11-17T00:29:53.380338 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:21:in `process_action'
F, [2016-11-17T00:29:53.380371 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
F, [2016-11-17T00:29:53.380402 #1873] FATAL -- : activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
F, [2016-11-17T00:29:53.380426 #1873] FATAL -- : actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
F, [2016-11-17T00:29:53.380445 #1873] FATAL -- : actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
F, [2016-11-17T00:29:53.380467 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
F, [2016-11-17T00:29:53.380489 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
F, [2016-11-17T00:29:53.380508 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
F, [2016-11-17T00:29:53.380543 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
F, [2016-11-17T00:29:53.380571 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
F, [2016-11-17T00:29:53.380594 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
F, [2016-11-17T00:29:53.380616 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
F, [2016-11-17T00:29:53.380638 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
F, [2016-11-17T00:29:53.380657 #1873] FATAL -- : exception_notification (4.2.1) lib/exception_notification/rack.rb:32:in `call'
F, [2016-11-17T00:29:53.380679 #1873] FATAL -- : warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
F, [2016-11-17T00:29:53.380703 #1873] FATAL -- : warden (1.2.6) lib/warden/manager.rb:34:in `catch'
F, [2016-11-17T00:29:53.380724 #1873] FATAL -- : warden (1.2.6) lib/warden/manager.rb:34:in `call'
F, [2016-11-17T00:29:53.380744 #1873] FATAL -- : rack (2.0.1) lib/rack/etag.rb:25:in `call'
F, [2016-11-17T00:29:53.380765 #1873] FATAL -- : rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
F, [2016-11-17T00:29:53.380786 #1873] FATAL -- : rack (2.0.1) lib/rack/head.rb:12:in `call'
F, [2016-11-17T00:29:53.380806 #1873] FATAL -- : rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
F, [2016-11-17T00:29:53.380826 #1873] FATAL -- : rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
F, [2016-11-17T00:29:53.380844 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
F, [2016-11-17T00:29:53.380863 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
F, [2016-11-17T00:29:53.380882 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
F, [2016-11-17T00:29:53.380902 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
F, [2016-11-17T00:29:53.380921 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
F, [2016-11-17T00:29:53.380948 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
F, [2016-11-17T00:29:53.380977 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
F, [2016-11-17T00:29:53.381004 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
F, [2016-11-17T00:29:53.381027 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
F, [2016-11-17T00:29:53.381047 #1873] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
F, [2016-11-17T00:29:53.381067 #1873] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
F, [2016-11-17T00:29:53.381088 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
F, [2016-11-17T00:29:53.381108 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
F, [2016-11-17T00:29:53.381201 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
F, [2016-11-17T00:29:53.381237 #1873] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
F, [2016-11-17T00:29:53.381264 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
F, [2016-11-17T00:29:53.381292 #1873] FATAL -- : rack (2.0.1) lib/rack/method_override.rb:22:in `call'
F, [2016-11-17T00:29:53.381319 #1873] FATAL -- : rack (2.0.1) lib/rack/runtime.rb:22:in `call'
F, [2016-11-17T00:29:53.381345 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
F, [2016-11-17T00:29:53.381374 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
F, [2016-11-17T00:29:53.381399 #1873] FATAL -- : rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
F, [2016-11-17T00:29:53.381425 #1873] FATAL -- : railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
F, [2016-11-17T00:29:53.381439 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
F, [2016-11-17T00:29:53.381451 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
F, [2016-11-17T00:29:53.381464 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
F, [2016-11-17T00:29:53.381475 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
F, [2016-11-17T00:29:53.381488 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by ewlarson** [comment]
Closing this issue. Too old to recall this issue. Any Qualys related issues can be recreated.
