### ISSUE TITLE
NoMethodError occurred in catalog#index: undefined method `each_pair' for "edit":String

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#5]
Qualys-generated error when hitting `GET /?action=data_management&cpmvc_do_action
=mvparse&weekstartday=alert%28String.fromCharCode%2881,85,65,76,89,83,88,83,83,84,69,83,84%29%`

some param parsing action fails expecting a Hash or Array when it receives a String.

##Request info:
```
-------------------------------
Request:
-------------------------------

  * URL        : https://lib-geoblacklight.oit.umn.edu/?action=data_management&cpmvc_do_action
=mvparse&weekstartday=alert%28String.fromCharCode%2881,85,65,76,89,83,88,83,83,84,69,83,84%29%
29&f=edit&id=1
  * HTTP Method: GET
  * IP address : 160.94.202.170
  * Parameters : {"action"=>"index", "cpmvc_do_action"=>"mvparse", "weekstartday"=>"alert(Stri
ng.fromCharCode(81,85,65,76,89,83,88,83,83,84,69,83,84))", "f"=>"edit", "id"=>"1",
"controller"=>"catalog"}
  * Timestamp  : 2016-11-17 00:30:14 -0600
  * Server : lib-geoblacklight.oit.umn.edu
  * Rails root : /swadm/usr/local/geoblacklight/releases/20161116144246
  * Process: 1873
```

##Trace:

```
F, [2016-11-17T00:30:14.222867 #1873] FATAL -- : NoMethodError (undefined method `each_pair' for "edit":String
Did you mean?  each_char):
, [2016-11-17T00:30:14.222894 #1873] FATAL -- :   
F, [2016-11-17T00:30:14.222983 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/solr/search_builder_behavior.rb:96:in `add_facet_fq_to_solr'
F, [2016-11-17T00:30:14.223011 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/search_builder.rb:147:in `block (2 levels) in processed_parameters'
F, [2016-11-17T00:30:14.223028 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/search_builder.rb:146:in `each'
F, [2016-11-17T00:30:14.223042 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/search_builder.rb:146:in `block in processed_parameters'
F, [2016-11-17T00:30:14.223057 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/search_builder.rb:145:in `tap'
F, [2016-11-17T00:30:14.223069 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/search_builder.rb:145:in `processed_parameters'
F, [2016-11-17T00:30:14.223081 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/search_builder.rb:119:in `to_hash'
F, [2016-11-17T00:30:14.223093 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/solr/repository.rb:38:in `block in send_and_receive'
F, [2016-11-17T00:30:14.223106 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/benchmarkable.rb:41:in `block in benchmark'
F, [2016-11-17T00:30:14.223118 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
F, [2016-11-17T00:30:14.223130 #1873] FATAL -- : /swadm/usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
F, [2016-11-17T00:30:14.223142 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
F, [2016-11-17T00:30:14.223154 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/benchmarkable.rb:41:in `benchmark'
F, [2016-11-17T00:30:14.223166 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/solr/repository.rb:36:in `send_and_receive'
F, [2016-11-17T00:30:14.223178 #1873] FATAL -- : blacklight (6.7.1) lib/blacklight/solr/repository.rb:22:in `search'
F, [2016-11-17T00:30:14.223190 #1873] FATAL -- : blacklight (6.7.1) app/controllers/concerns/blacklight/search_helper.rb:59:in `search_results'
F, [2016-11-17T00:30:14.223202 #1873] FATAL -- : blacklight (6.7.1) app/controllers/concerns/blacklight/catalog.rb:25:in `index'
F, [2016-11-17T00:30:14.223214 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
F, [2016-11-17T00:30:14.223227 #1873] FATAL -- : actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
F, [2016-11-17T00:30:14.223239 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
F, [2016-11-17T00:30:14.223251 #1873] FATAL -- : actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
F, [2016-11-17T00:30:14.223263 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
F, [2016-11-17T00:30:14.223281 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
F, [2016-11-17T00:30:14.223296 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
F, [2016-11-17T00:30:14.223308 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
F, [2016-11-17T00:30:14.223330 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
F, [2016-11-17T00:30:14.223344 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
F, [2016-11-17T00:30:14.223356 #1873] FATAL -- : actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
F, [2016-11-17T00:30:14.223368 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
F, [2016-11-17T00:30:14.223380 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
F, [2016-11-17T00:30:14.223393 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
F, [2016-11-17T00:30:14.223405 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
F, [2016-11-17T00:30:14.223417 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
F, [2016-11-17T00:30:14.223429 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
F, [2016-11-17T00:30:14.223495 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
F, [2016-11-17T00:30:14.223509 #1873] FATAL -- : activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
F, [2016-11-17T00:30:14.223521 #1873] FATAL -- : actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
F, [2016-11-17T00:30:14.223545 #1873] FATAL -- : actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
F, [2016-11-17T00:30:14.223563 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
F, [2016-11-17T00:30:14.223575 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
F, [2016-11-17T00:30:14.223587 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
F, [2016-11-17T00:30:14.223600 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
F, [2016-11-17T00:30:14.223612 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
F, [2016-11-17T00:30:14.223624 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
F, [2016-11-17T00:30:14.223636 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
F, [2016-11-17T00:30:14.223648 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
F, [2016-11-17T00:30:14.223660 #1873] FATAL -- : exception_notification (4.2.1) lib/exception_notification/rack.rb:32:in `call'
F, [2016-11-17T00:30:14.223672 #1873] FATAL -- : warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
F, [2016-11-17T00:30:14.223684 #1873] FATAL -- : warden (1.2.6) lib/warden/manager.rb:34:in `catch'
F, [2016-11-17T00:30:14.223696 #1873] FATAL -- : warden (1.2.6) lib/warden/manager.rb:34:in `call'
F, [2016-11-17T00:30:14.223707 #1873] FATAL -- : rack (2.0.1) lib/rack/etag.rb:25:in `call'
F, [2016-11-17T00:30:14.223718 #1873] FATAL -- : rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
F, [2016-11-17T00:30:14.223730 #1873] FATAL -- : rack (2.0.1) lib/rack/head.rb:12:in `call'
F, [2016-11-17T00:30:14.223741 #1873] FATAL -- : rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
F, [2016-11-17T00:30:14.223753 #1873] FATAL -- : rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
F, [2016-11-17T00:30:14.223764 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
F, [2016-11-17T00:30:14.223776 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
F, [2016-11-17T00:30:14.223788 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
F, [2016-11-17T00:30:14.223804 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
F, [2016-11-17T00:30:14.223817 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
F, [2016-11-17T00:30:14.223829 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
F, [2016-11-17T00:30:14.223841 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
F, [2016-11-17T00:30:14.223853 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
F, [2016-11-17T00:30:14.223873 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
F, [2016-11-17T00:30:14.223887 #1873] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
F, [2016-11-17T00:30:14.223899 #1873] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
F, [2016-11-17T00:30:14.223912 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
F, [2016-11-17T00:30:14.223924 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
F, [2016-11-17T00:30:14.223936 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
F, [2016-11-17T00:30:14.223948 #1873] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
F, [2016-11-17T00:30:14.223959 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
F, [2016-11-17T00:30:14.224012 #1873] FATAL -- : rack (2.0.1) lib/rack/method_override.rb:22:in `call'
F, [2016-11-17T00:30:14.224024 #1873] FATAL -- : rack (2.0.1) lib/rack/runtime.rb:22:in `call'
F, [2016-11-17T00:30:14.224035 #1873] FATAL -- : activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
F, [2016-11-17T00:30:14.224049 #1873] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
F, [2016-11-17T00:30:14.224062 #1873] FATAL -- : rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
F, [2016-11-17T00:30:14.224074 #1873] FATAL -- : railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
F, [2016-11-17T00:30:14.224085 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
F, [2016-11-17T00:30:14.224097 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
F, [2016-11-17T00:30:14.224109 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
F, [2016-11-17T00:30:14.224121 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
F, [2016-11-17T00:30:14.224133 #1873] FATAL -- : passenger (5.0.29) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by ewlarson** [comment]
Closing Qualys related issues. Reopen/Recreate if necessary.
